//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscussionForum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMENT
    {
        public int commentId { get; set; }
        public string commentDesc { get; set; }
        public Nullable<int> postId { get; set; }
        public Nullable<System.DateTime> postedDate { get; set; }
    
        public virtual POST POST { get; set; }
    }
}
